/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <cstrike>
#include <amxmisc>

#define PLUGIN "Models Selector"
#define VERSION "1.0"
#define AUTHOR "Emil"

new mMS // Menu
new mcbMS // Menu Callback


public showmenu(id){
  menu_display(id, mMS, 0);
}

public plugin_init() {
	/* Menu Выбор модели */
	/* Use menu_display(id, mВыбормодели, 0) to show the menu to an user. */
	mMS = menu_create("Выбор модели", "mh_MS")
	menu_additem(mMS, "Девушка ТТ", "ttgirl", ADMIN_ALL,-1)
	menu_additem(mMS, "Мужчина ТТ", "ttman", ADMIN_ALL,-1)
	menu_additem(mMS, "Девушка КТ", "ctgirl", ADMIN_ALL,-1)
	menu_additem(mMS, "Мужчина КТ", "ctman", ADMIN_ALL,-1)
	menu_addblank(mMS,0)
	menu_additem(mMS, "Стандартная модель", "modelback", ADMIN_ALL,-1)
	/* Menu End */

	register_plugin(PLUGIN, VERSION, AUTHOR)
	register_concmd("say /models","showmenu")
	register_concmd("models","showmenu")
	register_concmd("ttgirl","ttgirl")
	register_concmd("ttman","ttman")
	register_concmd("ctgirl","ctgirl")
	register_concmd("ctman","ctman")
	// Add your code here...
}


/* Menu Выбор модели */

public modelChanged(id){
	client_print(id,print_chat,"Модель изменена");
	menu_cancel(id)
}

public ttgirl(id){
	cs_set_user_model(id,"arctic-sanya");
}

public ttman(id){
	cs_set_user_model(id,"guerilla-sanya");
}

public ctman(id){
	cs_set_user_model(id,"urban-sanya");
}

public ctgirl(id){
	cs_set_user_model(id,"gign-sanya");
}

public mh_MS(id, menu, item) {
	new s_Data[30], s_Name[64], i_Access, i_Callback
	menu_item_getinfo(menu, item, i_Access, s_Data, charsmax(s_Data), s_Name, charsmax(s_Name), i_Callback)
	if(equal(s_Data,"ttgirl")){
		ttgirl(id)
		modelChanged(id)
	}else if(equal(s_Data,"ctgirl")){
		ctgirl(id)
		modelChanged(id)
	}else if(equal(s_Data,"ttman")){
		ttman(id)
		modelChanged(id)
	}else if(equal(s_Data,"ctman")){
		ctman(id)
		modelChanged(id)
	}else if(equal(s_Data,"modelback")){
		cs_reset_user_model(id);
		modelChanged(id)
	}
}

public ma_MS(id) {
	
}

public mcb_MS(id, menu, item) {
	return ITEM_ENABLED
}

/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1049\\ f0\\ fs16 \n\\ par }
*/
