/* Plugin generated by AMXX-Studio */

#include <cstrike>
#include <amxmodx>
#include <amxmisc>
#include <fun>
#include <fakemeta>

#define PLUGIN "Warmup"
#define VERSION "1.0"
#define AUTHOR "mrch3at"

new wmTime;

public plugin_init() {
	wmTime = 0;
	register_plugin(PLUGIN, VERSION, AUTHOR)
	set_task(1.0, "warmup", _, _, _, "a",65)
	register_event("TeamInfo", "onjoin", "a")
	register_cvar("mp_warmup", "0");
	set_cvar_num("mp_round_infinite", 1);
}

public showmessage(const str[]){
    set_dhudmessage(200, 100, 0, -1.0,  0.35,  0, 0, 0.1, 1.0);
    show_dhudmessage(0, str)
}

public onjoin(){
	new iPlayer = read_data(1)
	if (is_user_alive(iPlayer)) {
                  cs_set_user_money(iPlayer, 16000, 0);
         }
}

public warmup(){
	if(wmTime > 69) {return;}
	if(64-wmTime > 0){
		if(get_cvar_num("mp_warmup") == 0 && wmTime > 5){ wmTime = 69; return; }
		new str[255]
		format(str, 255, "Разминка: %d", 65-wmTime)
		showmessage(str)
		set_cvar_num("mp_round_infinite", 1);
		set_cvar_num("mp_forcerespawn", 1);
		set_cvar_num("mp_warmup", 1);
		wmTime+=1;
	}else{
		server_cmd("sv_restartround 1")
		showmessage("Разминка завершена")
		set_cvar_num("mp_forcerespawn", 0);
		set_cvar_num("mp_round_infinite", 0);
		set_cvar_num("mp_warmup", 0);
		wmTime = 99;
	}
}
